String webpage = "<!DOCTYPE html>"
"<html lang='en'>"
"  <head>"
"    <meta charset='UTF-8' />"
"    <meta name='viewport' content='width=device-width, initial-scale=1.0' />"
"    <title>Drive</title>"
"    <style>"
"      button {"
"        font-size: 20px;"
"        padding: 10px;"
"        margin: 10px;"
"      }"
"    </style>"
"  </head>"
"  <body>"
"    <button>STRAIGHT</button>"
"    <button>LEFT</button>"
"    <button>RIGHT</button>"
"    <button>BACK</button>"
"    <script>"
"      const buttons = document.querySelectorAll('button');"
"      buttons.forEach((button) => {"
"        button.addEventListener('click', (e) => {"
"          fetch('/path', {"
"            method: 'POST',"
"            body: e.target.textContent.toLowerCase(),"
"          });"
"        });"
"      });"
"    </script>"
"  </body>"
"</html>";
